DROP TABLE persona IF EXISTS;
CREATE TABLE persona ( id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
                        identificacion varchar(100) NOT NULL,
                        nombre varchar(100) NOT NULL,
                        apellido varchar(100) NOT NULL,
                        PRIMARY KEY (id) ); 
